version: '2'
services:
    docker-nginx-letsencrypt-proxy:
        build: .
        image: annixa/docker-nginx-letsencrypt-proxy:build
        ports:
            - 80:80
            - 8443:8443
        container_name: docker-nginx-letsencrypt-proxy
        logging:
            options:
                max-size: 50k
        environment:
            - LE_EMAIL=test@test.com
            - LE_DOMAIN=example.com
            - PROXY_DEST=http://google.com
            - PROXY_PORT=8443
        volumes:
        # - "/etc/letsencrypt"
        # links:
        #   - mycontainer
        # Be sure to link your container!
